![banner](../static/banner.png)

---

# Part 2 - Learning the ropes of coding in R  👩‍💻

If you've never coded before, haven't had much practice or are new to R in particular, don't fret! Below, we introduce all the bits and pieces you need in order to understand our neural network code. Run the cells below to see how R works.

## Arithmetic
We can use R like a calculator to perform simple arithmetic. 

In [28]:
3 + 4
4 - 7
3.6 * 4.2
-3 / pi
2 + 2 == 5

[1] 7

[1] -3

[1] 15.12

[1] -0.9549297

[1] FALSE

**Note:** Lines of code with a `#` out the front are called **comments**. Comments are ignored by the computer when it runs code, and are used to help explain things about the code to other humans.

In [2]:
# The line below will not result in a 4 being printed, as it's not code, it's a comment. 
# 2 + 2

# But 5 will be printed!
2 + 3

[1] 5

## Variables
Variables can be used to store data, so that it can be referenced again later on. For example, say we wanted to create a variable called `lucky_number` and we wanted to store in this variable the value `8`.

In [8]:
lucky_number = 8

We might not use that value now, but it is stored so we can use it later. Let's try printing it now:

In [9]:
lucky_number

[1] 8

Variables can be used inplace of wherever you would normally use their contents. For example, if we have a variable that holds ad number, we can use it in arithmetic.

In [11]:
unlucky_number = 4 

lucky_number + unlucky_number

[1] 12

Note that while most programming languages use `=` to assign a value to a variable, you may see R code use the `<-` symbol instead. Both `=` and `<-` can be used in R, but the latter is pretty unique to R, so for this session we'll just stick to `=`.

In [16]:
route <- 66
route

[1] 66

## Data types
When programming we use more than just numbers! The number `8` and the word `lucky` can both be considered data, but they're quite different in form and how they can be used. While we know how to halve `8`, what would it mean to halve the word `lucky`? Programming langauges often categorise data based on their structure and uses into what are called **data types**. 

Some of the more common data types include:

- Integers, like `8`
- Decimal numbers, like `2.421`
- Strings (an ordered arrangement of characters), like `I <3 memes!`
- Vectors (collections of objects of the same type), like `[1, 2, 3]`
- Boolean values, either `True` or `False`

There are many more types, and they are all often given slightly different names by different languages. 

In practice, strings in R are written enclosed in `"quotation marks"`, vectors written like inside a pair of brackets with a c at the front, `c()`, and booleans as `TRUE` and `FALSE`.

In [32]:
DPA_overdue = TRUE # Boolean (or logical)
why = "does skype refuse to share my screen" # String
rest_and_stretch_breaks = 6.3 # Decimal (or numeric)
free_tea_bags = 0 # Integer
sequence = c(1,1,2,3,5,8,13,21,34,55) # Vector

We can access the **elements** (entries) in a vector by using the position it is in:

In [35]:
sequence[1]
sequence[3]
sequence[1:4]

[1] 1

[1] 2

[1] 1 1 2 3

### Lists and matrices
Two data types that we'll use a lot to create our neural network are **lists** and **matrices**. 

Lists are similar to vectors, in that they can be used to bundle a bunch of data together into one object. One big difference is that lists can hold different data types, while vectors only hold objects of the same type. Another key difference is that we can give elements in a list a name, and then access them by that name.

- Concept of lists and matrices
- How to create a list
- How to create a matrix
- How to view a list or matrix
- How to access elements of a list/matrix

In [9]:
my_favs = list(colour = "green", number = 8, sequence = c(1,1,2,3,5,8,13,21,34,55), workplace = "ABS", R_function = abs)

In [10]:
my_favs

$colour
[1] "green"

$number
[1] 8

$sequence
 [1]  1  1  2  3  5  8 13 21 34 55

$workplace
[1] "ABS"

$R_function
function (x)  .Primitive("abs")

In [11]:
my_favs$colour
my_favs[["sequence"]]

[1] "green"

[1]  1  1  2  3  5  8 13 21 34 55

In [12]:
my_matrix = matrix(seq(5, 200, 5), nrow = 5)
my_matrix

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  5   30   55    80  105  130  155  180 
[2,] 10   35   60    85  110  135  160  185 
[3,] 15   40   65    90  115  140  165  190 
[4,] 20   45   70    95  120  145  170  195 
[5,] 25   50   75   100  125  150  175  200

In [13]:
ncol(my_matrix)
my_matrix[1, 3]
my_matrix[1, ]
my_matrix[, 5]
my_matrix[1:3, 1:2]
t(my_matrix)

[1] 8

[1] 55

[1]   5  30  55  80 105 130 155 180

[1] 105 110 115 120 125

[,1] [,2]
[1,]  5   30  
[2,] 10   35  
[3,] 15   40

[,1] [,2] [,3] [,4] [,5]
[1,]   5   10   15   20   25 
[2,]  30   35   40   45   50 
[3,]  55   60   65   70   75 
[4,]  80   85   90   95  100 
[5,] 105  110  115  120  125 
[6,] 130  135  140  145  150 
[7,] 155  160  165  170  175 
[8,] 180  185  190  195  200

## Loops <a name="loops"></a>
- Concept of loops
- How to write a for loop

## Functions <a name="functions"></a>
- Concept of functions
- How to write a function
- Concept of packages
- How to load a package
- Examples of functions (print, library, random number generation)

---
## ↪️ Next up: [Part 3 🔎 - Revising the basics of neural networks](./3_Revising_NNs.ipynb)