# ABS - Intro to Neural Networks Learning Session
---
## Part 2 - Learn the ropes of coding in R  👩‍💻
If you've never coded before, haven't had much practice or are new to R in particular, don't fret! Below, we introduce all the bits and pieces you need in order to understand our neural network code.

#### Arithmetic

In [21]:
# This is a comment! Arithmetic in R is simple.
3 + 4
4 - 7
3.6 * 4.2
-3 / pi

[1] 7

[1] -3

[1] 15.12

[1] -0.9549297

#### Data types

In [48]:
8
2.2
"hello!"
c(1,2, "word")

[1] 8

[1] 2.2

[1] "hello!"

[1] "1"    "2"    "word"

In [49]:
seq
print

function (...) 
UseMethod("seq")
<bytecode: 0x55635c3b0878>
<environment: namespace:base>

function (x, ...) 
UseMethod("print")
<bytecode: 0x55635f8986d0>
<environment: namespace:base>

In [60]:
seq(1,10,2)

[1] 1 3 5 7 9

In [61]:
class(seq(1,10,2))
class(print)

[1] "numeric"

[1] "function"

#### Variables <a name="variables"></a>
- Concept of a variable
- How to assign variables (mention that in R, <- is often used, but for today we're going to use = as its more common)
- How to view/print variables

In [38]:
a = 7
b = a - 3
c <- "dog"
d = a * b

In [36]:
c

[1] "dog"

In [39]:
print(d)

[1] 28


#### Lists and matrices <a name="listsandmatrices"></a>
- Concept of lists and matrices
- How to create a list
- How to create a matrix
- How to view a list or matrix
- How to access elements of a list/matrix

In [80]:
my_favs = list(colour = "green", number = 8, sequence = c(1,1,2,3,5,8,13,21,34,55), workplace = "ABS", R_function = abs)

In [81]:
my_favs

$colour
[1] "green"

$number
[1] 8

$sequence
 [1]  1  1  2  3  5  8 13 21 34 55

$workplace
[1] "ABS"

$R_function
function (x)  .Primitive("abs")

In [82]:
my_favs$colour
my_favs[["sequence"]]

[1] "green"

[1]  1  1  2  3  5  8 13 21 34 55

In [86]:
my_matrix = matrix(seq(5, 200, 5), nrow = 5)
my_matrix

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  5   30   55    80  105  130  155  180 
[2,] 10   35   60    85  110  135  160  185 
[3,] 15   40   65    90  115  140  165  190 
[4,] 20   45   70    95  120  145  170  195 
[5,] 25   50   75   100  125  150  175  200

In [94]:
ncol(my_matrix)
my_matrix[1, 3]
my_matrix[1, ]
my_matrix[, 5]
my_matrix[1:3, 1:2]
t(my_matrix)

[1] 8

[1] 55

[1]   5  30  55  80 105 130 155 180

[1] 105 110 115 120 125

[,1] [,2]
[1,]  5   30  
[2,] 10   35  
[3,] 15   40

[,1] [,2] [,3] [,4] [,5]
[1,]   5   10   15   20   25 
[2,]  30   35   40   45   50 
[3,]  55   60   65   70   75 
[4,]  80   85   90   95  100 
[5,] 105  110  115  120  125 
[6,] 130  135  140  145  150 
[7,] 155  160  165  170  175 
[8,] 180  185  190  195  200

#### Loops <a name="loops"></a>
- Concept of loops
- How to write a for loop

#### Functions <a name="functions"></a>
- Concept of functions
- How to write a function
- Concept of packages
- How to load a package
- Examples of functions (print, library, random number generation)

---
## Next up ⤵️
### [Part 3 - Using neural networks to classify handwritten digits](./3_Neural_Networks.ipynb)