![banner](../static/banner.png)

---

# Part 2 - Learning the ropes of coding in R  👩‍💻

If you've never coded before, haven't had much practice or are new to R in particular, don't fret! Below, we introduce all the bits and pieces you need in order to understand our neural network code. Run the cells below to see how R works.

## Arithmetic
We can use R like a calculator to perform simple arithmetic. 

In [28]:
3 + 4
4 - 7
3.6 * 4.2
-3 / pi
2 + 2 == 5

[1] 7

[1] -3

[1] 15.12

[1] -0.9549297

[1] FALSE

**Note:** Lines of code with a `#` out the front are called **comments**. Comments are ignored by the computer when it runs code, and are used to help explain things about the code to other humans.

In [2]:
# The line below will not result in a 4 being printed, as it's not code, it's a comment. 
# 2 + 2

# But 5 will be printed!
2 + 3

[1] 5

## Variables
Variables can be used to store data, so that it can be referenced again later on. For example, say we wanted to create a variable called `lucky_number` and we wanted to store in this variable the value `8`.

In [8]:
lucky_number = 8

We might not use that value now, but it is stored so we can use it later. Let's try printing it now:

In [9]:
lucky_number

[1] 8

Variables can be used inplace of wherever you would normally use their contents. For example, if we have a variable that holds ad number, we can use it in arithmetic.

In [11]:
unlucky_number = 4 

lucky_number + unlucky_number

[1] 12

Note that while most programming languages use `=` to assign a value to a variable, you may see R code use the `<-` symbol instead. Both `=` and `<-` can be used in R, but the latter is pretty unique to R, so for this session we'll just stick to `=`.

In [16]:
route <- 66

route

[1] 66

## Data types
When programming we use more than just numbers! The number `8` and the word `lucky` can both be considered data, but they're quite different in form and how they can be used. While we know how to halve `8`, what would it mean to halve the word `lucky`? Programming langauges often categorise data based on their structure and uses into what are called **data types**. 

Some of the more common data types include:

- Integers, like `8`
- Decimal numbers, like `2.421`
- Strings (an ordered arrangement of characters), like `I <3 memes!`
- Vectors (collections of objects of the same type), like `[1, 2, 3]`
- Boolean values, either `True` or `False`

There are many more types, and they are all often given slightly different names by different languages. 

In practice, strings in R are written enclosed in `"quotation marks"`, vectors written like inside a pair of brackets with a c at the front, `c()`, and booleans as `TRUE` and `FALSE`.

In [1]:
DPA_overdue = TRUE # Boolean (or logical)
why = "does skype refuse to share my screen" # String
rest_and_stretch_breaks = 6.3 # Decimal (or numeric)
free_tea_bags = 0 # Integer
sequence = c(1,1,2,3,5,8,13,21,34,55) # Vector

We can access the **elements** (entries) in a vector by using the position it is in:

In [35]:
sequence[1]
sequence[3]
sequence[1:4]

[1] 1

[1] 2

[1] 1 1 2 3

### Lists and matrices
Two data types that we'll use a lot to create our neural network are **lists** and **matrices**. 

**Lists** are similar to vectors, in that they can be used to bundle a bunch of pieces of data together into one object. There are two key differences for our purposes:
1. Lists can hold different data that differ in type (e.g a list can hold both numbers and strings), while vectors only hold objects of the same type. If you try to place data of more than one type into a vector, it will convert the data in a way that makes all entries the same type.
2. In lists, data entries can be given a name, and then accessed them by that name, while data in vectors can only be accessed be referencing it's position in the vector.

To creat a list, we type `list(name_1 = data_1, name_2 = data_2, ..., name_n = data_n)`, where the names are what you want to call the data you are storing, and `n` can be any positive whole number. For example, we could use a list to store some information about Aka the tortoise.

In [12]:
animal_1 = list(
    name = "Aka", 
    age = 71, 
    species = "Tortoise", 
    icon = "🐢", 
    health_conditions = FALSE, 
    dimensions = list(length = 80, width = 50, height = 40)
)
animal_1

$name
[1] "Aka"

$age
[1] 71

$species
[1] "Tortoise"

$icon
[1] "🐢"

$health_conditions
[1] FALSE

$dimensions
$dimensions$length
[1] 80

$dimensions$width
[1] 50

$dimensions$height
[1] 40

We can then use the names we gave to the data to easily access what we want. There are two ways to do this, one using the `$` symbol, and the other using double square brackets, `[[...]]`. Both are shown below, but for today, we'll just use the `$` method.

In [13]:
# Both ways give us the 
animal_1$icon
animal_1[["icon"]]

[1] "🐢"

[1] "🐢"

We can even put lists inside lists, and get the data we want using the same idea.

In [14]:
animal_1$dimensions
animal_1$dimensions$length

$length
[1] 80

$width
[1] 50

$height
[1] 40

[1] 80

In [12]:
my_matrix = matrix(seq(5, 200, 5), nrow = 5)
my_matrix

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  5   30   55    80  105  130  155  180 
[2,] 10   35   60    85  110  135  160  185 
[3,] 15   40   65    90  115  140  165  190 
[4,] 20   45   70    95  120  145  170  195 
[5,] 25   50   75   100  125  150  175  200

In [13]:
ncol(my_matrix)
my_matrix[1, 3]
my_matrix[1, ]
my_matrix[, 5]
my_matrix[1:3, 1:2]
t(my_matrix)

[1] 8

[1] 55

[1]   5  30  55  80 105 130 155 180

[1] 105 110 115 120 125

[,1] [,2]
[1,]  5   30  
[2,] 10   35  
[3,] 15   40

[,1] [,2] [,3] [,4] [,5]
[1,]   5   10   15   20   25 
[2,]  30   35   40   45   50 
[3,]  55   60   65   70   75 
[4,]  80   85   90   95  100 
[5,] 105  110  115  120  125 
[6,] 130  135  140  145  150 
[7,] 155  160  165  170  175 
[8,] 180  185  190  195  200

## Loops <a name="loops"></a>
- Concept of loops
- How to write a for loop

## Functions <a name="functions"></a>
- Concept of functions
- How to write a function
- Concept of packages
- How to load a package
- Examples of functions (print, library, random number generation)

---
## ↪️ Next up: [Part 3 🔎 - Revising the basics of neural networks](./3_Revising_NNs.ipynb)